# Generated by Django 5.2.5 on 2025-08-14 18:13

import django.db.models.deletion
import patients.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('READ', 'Lecture'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('EXPORT', 'Export de données')], max_length=10)),
                ('model_name', models.CharField(max_length=100, verbose_name='Modèle concerné')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='ID objet')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Représentation objet')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Modifications')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', patients.models.EncryptedField(verbose_name='Prénom')),
                ('last_name', patients.models.EncryptedField(verbose_name='Nom')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, verbose_name='Sexe')),
                ('social_security_number', patients.models.EncryptedField(blank=True, verbose_name='Numéro de sécurité sociale')),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Célibataire'), ('MARRIED', 'Marié(e)'), ('DIVORCED', 'Divorcé(e)'), ('WIDOWED', 'Veuf/Veuve')], max_length=20, verbose_name='Situation familiale')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('address', patients.models.EncryptedField(blank=True, verbose_name='Adresse')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('phone', patients.models.EncryptedField(blank=True, verbose_name='Téléphone')),
                ('mobile', patients.models.EncryptedField(blank=True, verbose_name='Mobile')),
                ('email', patients.models.EncryptedField(blank=True, verbose_name='Email')),
                ('emergency_contact_name', patients.models.EncryptedField(blank=True, verbose_name="Contact d'urgence - Nom")),
                ('emergency_contact_phone', patients.models.EncryptedField(blank=True, verbose_name="Contact d'urgence - Téléphone")),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, verbose_name='Lien de parenté')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('medical_history', models.TextField(blank=True, verbose_name='Antécédents médicaux')),
                ('current_medications', models.TextField(blank=True, verbose_name='Médicaments actuels')),
                ('medical_notes', models.TextField(blank=True, verbose_name='Notes médicales')),
                ('insurance_name', models.CharField(blank=True, max_length=100, verbose_name='Nom mutuelle')),
                ('insurance_number', patients.models.EncryptedField(blank=True, verbose_name='Numéro adhérent')),
                ('rgpd_consent', models.BooleanField(default=False, verbose_name='Consentement RGPD')),
                ('rgpd_consent_date', models.DateTimeField(blank=True, null=True, verbose_name='Date consentement RGPD')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='Consentement marketing')),
                ('patient_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro patient')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
